
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dwambugu
 */
public class myRoomsFrame extends javax.swing.JFrame {

    String userID;
    String roomPrice = null;
    String bookingID = null;
    String firstName;
    String roomID;
    String roomNum;
    String roomType;

    Connection dbconn = DatabaseConnection.connectDB();
    
    /**
     * Creates new form myRoomsFrame
     */
    public myRoomsFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public myRoomsFrame(String userID, String firstName) {
        initComponents();
        this.setLocationRelativeTo(null);
                
        this.userID = userID;
        this.firstName = firstName;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        updateBookingsBtn = new javax.swing.JButton();
        roomNoField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roomTypeField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        roomPriceField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        amountPayableField = new javax.swing.JTextField();
        cancelBookBtn = new javax.swing.JButton();
        calcAmountBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        myRoomsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("My Room(s)");

        welcomeLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(255, 255, 255));

        homeBtn.setBackground(new java.awt.Color(255, 102, 0));
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        updateBookingsBtn.setBackground(new java.awt.Color(0, 0, 0));
        updateBookingsBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateBookingsBtn.setForeground(new java.awt.Color(255, 102, 0));
        updateBookingsBtn.setText("Update Booking");
        updateBookingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBookingsBtnActionPerformed(evt);
            }
        });

        roomNoField.setEditable(false);

        jLabel1.setText("Room No");

        jLabel3.setText("Room Type ");

        roomTypeField.setEditable(false);

        jLabel4.setText("Checkin Date");

        jLabel5.setText("Room Price ");

        roomPriceField.setEditable(false);

        jLabel6.setText("Checkout Date");

        jLabel7.setText("Amount Payable");

        amountPayableField.setEditable(false);

        cancelBookBtn.setBackground(new java.awt.Color(0, 0, 0));
        cancelBookBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBookBtn.setForeground(new java.awt.Color(204, 102, 0));
        cancelBookBtn.setText("Cancel Room");
        cancelBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBookBtnActionPerformed(evt);
            }
        });

        calcAmountBtn.setBackground(new java.awt.Color(0, 0, 0));
        calcAmountBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        calcAmountBtn.setForeground(new java.awt.Color(204, 102, 0));
        calcAmountBtn.setText("Calculate Amount");
        calcAmountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcAmountBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roomNoField, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(roomTypeField)
                            .addComponent(roomPriceField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(updateBookingsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(calcAmountBtn)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(amountPayableField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(amountPayableField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(roomNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBookingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcAmountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        myRoomsTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        myRoomsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Room Number", "Room Type", "Booking Date", "CheckIn Date", "CheckOut Date", "Amount Paid", "Booking Status", "ID", "rmID"
            }
        ));
        myRoomsTable.setAutoscrolls(false);
        myRoomsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myRoomsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(myRoomsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Method to populate table with Booked Rooms
    protected void populateTable(){
         try{
           
            PreparedStatement pst = (PreparedStatement)
                    dbconn.prepareStatement(
                   "SELECT `bookingDate`, `ckeckInDate`,`checkOutDate`, `amountPayable`, `bookingIsComplete`,"
                    + " `roomNum`, `roomTypeName`, `roomTypePrice`, `bookingID`, `bookings`.`roomID` FROM `bookings` INNER JOIN room on "
                    + "bookings.roomID = room.roomID INNER JOIN roomtype ON room.roomTypeID = roomtype.roomTypeID "
                    + "WHERE bookings.userID = '"+userID+"' ;");
                        
            ResultSet rs = pst.executeQuery();
            
            // Store db values in some variables
            String bookingStatus = null;
            
            if(rs.next()){
                bookingStatus = rs.getString("bookingIsComplete");
                roomPrice = rs.getString("roomTypePrice");
                //roomID = rs.getString("roomID");
            }else{
                JOptionPane.showMessageDialog(null, "No data Found");
            }
            
            //JOptionPane.showMessageDialog(null, roomID);
                        
            String bookingStatusVal = "";
            
            //Covert Booking Status to String
            if ("1".equals(bookingStatus)) {
                bookingStatusVal = "Complete";
            } else {
                bookingStatusVal = "Incomplete";
            }
            
            DefaultTableModel model = (DefaultTableModel)myRoomsTable.getModel();
            model.setRowCount(0);
            
            
            while(rs.next()){
               model.addRow(new String[] {rs.getString(6), rs.getString(7), rs.getString(1), rs.getString(2), 
                    rs.getString(3), rs.getString(4), bookingStatusVal, rs.getString(9), rs.getString(10)}); 
            }
                        
            
        }
        catch (SQLException ex) {
//            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);   
              JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    // set room to available    
    public void setRoomIsAvailableState(){
       try{
          
           //update the roomIsAvailable Value in the database
           String sql = "UPDATE `room` SET `roomIsAvailable` = 1 WHERE `roomID` = '"+roomID+"'";
           PreparedStatement pst = (PreparedStatement)
                   dbconn.prepareStatement(sql);
           //pst.setString(1, roomID);

           pst.execute();

           JOptionPane.showMessageDialog(null, "Updating rooms was Successful!");
       }
       catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
       }
    }
      
    
    //Delete booking entry from booking table
    private void cancelBooking(){
        try{
           
            PreparedStatement pst = (PreparedStatement)
                    dbconn.prepareStatement("DELETE FROM `bookings` WHERE `bookings`.`bookingID` = '"+bookingID+"';");
            
            pst.executeUpdate();
                                   
            JOptionPane.showMessageDialog(this, "Room Cancelation was successfull!");
            
        }
        catch (SQLException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);        
        }        
        
    }
    
    private void updateBookingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBookingsBtnActionPerformed

        

    }//GEN-LAST:event_updateBookingsBtnActionPerformed

    private void cancelBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBookBtnActionPerformed
        
        //Confirm booking Cancelation
        int response;
        response = JOptionPane.showConfirmDialog(this, "Are you sure to cancel booking with booking ID " + bookingID + "?", 
        "Confirm", JOptionPane.YES_NO_OPTION);
        
        if (response == JOptionPane.YES_OPTION) {
            cancelBooking();
            
            JOptionPane.showMessageDialog(null, roomNum);
        
            populateTable();
        
            setRoomIsAvailableState();
        } else {
        }

    }//GEN-LAST:event_cancelBookBtnActionPerformed

    private void calcAmountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcAmountBtnActionPerformed
        
    }//GEN-LAST:event_calcAmountBtnActionPerformed

    private void myRoomsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myRoomsTableMouseClicked
        
               
        
        int rowData = myRoomsTable.getSelectedRow();
        TableModel model = myRoomsTable.getModel();
        
        roomNum = model.getValueAt(rowData,0).toString();
        roomType = model.getValueAt(rowData,1).toString(); 
        bookingID = model.getValueAt(rowData,7).toString(); 
        roomID = model.getValueAt(rowData,8).toString();
        
        JOptionPane.showMessageDialog(this, bookingID);
        
        // Populate textfields with values from the selected row
        roomNoField.setText(roomNum);
        roomTypeField.setText(roomType);
        roomPriceField.setText(roomPrice);
     

    }//GEN-LAST:event_myRoomsTableMouseClicked

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        UserDashboard udash = new UserDashboard(userID, firstName);
        this.dispose();
        udash.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myRoomsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myRoomsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myRoomsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myRoomsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myRoomsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountPayableField;
    private javax.swing.JButton calcAmountBtn;
    private javax.swing.JButton cancelBookBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable myRoomsTable;
    private javax.swing.JTextField roomNoField;
    private javax.swing.JTextField roomPriceField;
    private javax.swing.JTextField roomTypeField;
    private javax.swing.JButton updateBookingsBtn;
    protected javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
